// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJKN36jo1WfUlBs8iAV6GZaMAQjNrG5V0',
    appId: '1:754441165761:web:931b87d9bf394927f0ad40',
    messagingSenderId: '754441165761',
    projectId: 'milkotea-virac',
    authDomain: 'milkotea-virac.firebaseapp.com',
    storageBucket: 'milkotea-virac.firebasestorage.app',
    measurementId: 'G-JCQFB9SYSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8wn8dLni0VOa5uDDNpngojPCwwcZKzcc',
    appId: '1:754441165761:android:12e02116454801e5f0ad40',
    messagingSenderId: '754441165761',
    projectId: 'milkotea-virac',
    storageBucket: 'milkotea-virac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxFYHxKpeLrc6fSPCpLUIRuIsmK6L5Uto',
    appId: '1:754441165761:ios:66a157bf8490e197f0ad40',
    messagingSenderId: '754441165761',
    projectId: 'milkotea-virac',
    storageBucket: 'milkotea-virac.firebasestorage.app',
    iosClientId: '754441165761-ppbdri4dbqtm7rl3kbpn7ht1t3itb6i2.apps.googleusercontent.com',
    iosBundleId: 'com.example.milkteaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxFYHxKpeLrc6fSPCpLUIRuIsmK6L5Uto',
    appId: '1:754441165761:ios:66a157bf8490e197f0ad40',
    messagingSenderId: '754441165761',
    projectId: 'milkotea-virac',
    storageBucket: 'milkotea-virac.firebasestorage.app',
    iosClientId: '754441165761-ppbdri4dbqtm7rl3kbpn7ht1t3itb6i2.apps.googleusercontent.com',
    iosBundleId: 'com.example.milkteaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJKN36jo1WfUlBs8iAV6GZaMAQjNrG5V0',
    appId: '1:754441165761:web:0cae404709e8159bf0ad40',
    messagingSenderId: '754441165761',
    projectId: 'milkotea-virac',
    authDomain: 'milkotea-virac.firebaseapp.com',
    storageBucket: 'milkotea-virac.firebasestorage.app',
    measurementId: 'G-4CPG7S1GB2',
  );
}
